# Generated by Django 5.0.1 on 2024-02-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zenjottapp', '0003_remove_mood_rating_journalentry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='update_time',
        ),
        migrations.AddField(
            model_name='communitypost',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
