# Generated by Django 5.0.1 on 2024-02-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zenjottapp', '0004_remove_comment_update_time_communitypost_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default=None),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
