# Generated by Django 5.0.1 on 2024-02-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zenjottapp', '0005_remove_comment_comment_comment_content_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
